export const items =  [
    {
      id: 1,
      category: 'mens',
      title: "Khaadi",
      imgSrc: 'https://th.bing.com/th/id/OIP.JVM28r7dRlHx5v5ERGHrWAHaHa?pid=ImgDet&w=175&h=175&c=7&dpr=1.5',
      amazonLink: 'https://amzn.to/3PuckZp',
      description: 'Plain Party Wear shirt',
      price: '2999',
    },
    {
      id: 5,
      category: 'womens',
      title: "FashionStyle",
      imgSrc: 'https://th.bing.com/th/id/OIP.T75Q74FSa5gzbcBwxT88QwHaIo?w=195&h=227&c=7&r=0&o=5&dpr=1.5&pid=1.7',
      amazonLink: 'https://amzn.to/3EzeQaC',
      description: 'Appealing Women Deming Shirt',
      price: '1999',
    },
    {
      id: 7,
      category: 'child',
      title: "Child World",
      imgSrc: 'https://th.bing.com/th/id/OIP.Dv339g5hKF_0GGiuZnbvHgHaHa?rs=1&pid=ImgDetMain',
      amazonLink: 'https://amzn.to/3ZeNRdY',
      description: 'Girls cloth set for Summer',
      price: '3999',
    },
    {
      id: 2,
      category: 'mens',
      title: "Bonanza",
      imgSrc: 'https://th.bing.com/th/id/OIP.2_dc9PrUweJvh7ZV4uRzFgHaJo?rs=1&pid=ImgDetMain',
      amazonLink: 'https://amzn.to/44MiYi6',
      description: 'Men Plain slim fit formal shirt - White',
      price: '7999',
    },
    {
      id: 6,
      category: 'child',
      title: "BoysWear",
      imgSrc: 'https://i.pinimg.com/originals/5d/23/42/5d234221ee76a055ebfa9f3c514876b2.jpg',
      amazonLink: 'https://amzn.to/3RabsdH',
      description: 'Dressy outfit for kids',
      price: '5999',
    },
    {
      id: 3,
      category: 'mens',
      title: "J. by Junaid Jamshed",
      imgSrc: 'https://th.bing.com/th/id/OIP.DFEwldzMsd74lQ5wCdl7QQHaJo?pid=ImgDet&w=175&h=227&c=7&dpr=1.5',
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'Striped Regular fit shirt- Blue',
      price: '6999',
    },
    {
      id: 4,
      category: 'womens',
      title: "Sana Safinaz",
      imgSrc: 'https://th.bing.com/th/id/R.d598eaad129f6c5b77f32945286dc393?rik=Imak4yKorOKEiQ&pid=ImgRaw&r=0',
      amazonLink: 'https://amzn.to/44JsK4r',
      description: 'Cotton Strech plain Women Shirt',
      price: '8999',
    },
    {
      id: 9,
      category: 'child',
      title: "Sports Wear",
      imgSrc: 'https://th.bing.com/th/id/OIP.0q6NwM7QnPgm5PyeEumB6gHaHa?rs=1&pid=ImgDetMain',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'Boys Clothing set SportsWear',
      price: '8999',
    },
    {
      id: 8,
      category: 'womens',
      title: "HRS cloths",
      imgSrc: 'https://th.bing.com/th/id/OIP.n3_23-uARfxSAByYVScbkgHaLH?rs=1&pid=ImgDetMain',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Embroidered Everday Plain Shirt',
      price: '3999',
    },


  ]